services:
  # Contenedor para pruebas
  test-container:
    build:
      context: .
      dockerfile: Dockerfile.test
    profiles:
      - testing
    networks:
      - shared-network

  # Servidor de Aplicación
  app-server:
    build:
      context: .
      dockerfile: Dockerfile.app
    ports:
      - "8080:8080"
    profiles:
      - application
    networks:
      - shared-network

  #Servidor de Pruebas Automatizadas
  test-runner:
    build:
      context: .
      dockerfile: Dockerfile.automationTest
    environment:
      TEST_ENV: "integration"
    profiles:
      - automation
    networks:
      - shared-network

  # Servidor de Jenkins
  jenkins:
    image: jenkins/jenkins:lts
    ports:
      - "8081:8080"       
      - "50000:50000"
    volumes:
      - jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
      - /usr/bin/docker-compose:/usr/bin/docker-compose
    profiles:
      - jenkins
    environment:
      - JAVA_OPTS=-Djenkins.install.runSetupWizard=false
    networks:
      - shared-network

volumes:
  jenkins_home:

networks:
  shared-network:
    driver: bridge
