# Usa una imagen base de Maven con JDK 17 para ejecutar pruebas en Java
FROM maven:3.8-openjdk-17

# Establece el directorio de trabajo en el contenedor
WORKDIR /app

# Copia el archivo `pom.xml` y otros archivos de configuración de Maven
COPY pom.xml ./

# Descarga las dependencias sin construir el proyecto
RUN mvn dependency:go-offline

# Copia todo el código fuente al contenedor
COPY src ./src

# Ejecuta las pruebas
CMD ["mvn", "test"]
