# Usar una imagen base que incluya un navegador (Chromium en este caso)
FROM seleniarm/standalone-chromium

# Instalar Maven
USER root
RUN apt-get update && \
    apt-get install -y openjdk-17-jdk maven && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*

# Opcional: establece JAVA_HOME
ENV JAVA_HOME /usr/lib/jvm/java-17-openjdk-arm64
ENV PATH $JAVA_HOME/bin:$PATH

# Cambiar al usuario original de Selenium
USER seluser